### ISSUE TITLE
Windows 10 on 200% HiDPI display has visual errors

### ISSUE THREAD

**Issue by Bosch-0** [bitcoin-core/gui#117]
200% (HiDPI) on Windows has issues on master 9af7c19.

![image](https://user-images.githubusercontent.com/55287964/97265883-5d883000-1862-11eb-977e-24eaa8a829d5.png)

**Comment by jarolrod** [comment]
Can you provide some more information behind this?

Cannot replicate on a VM with Windows 10 20H2 and 200% HIDPI:
![windows-hidpi-error](https://user-images.githubusercontent.com/23396902/104830016-15b4eb80-5848-11eb-9832-a194e5597699.png)

**Comment by jarolrod** [comment]
@Bosch-0 is this still a problem for you?

**Comment by jonasschnelli** [comment]
@Bosch-0: What Qt version was used for that screenshot?

**Comment by Bosch-0** [comment]
@Bosch-0 just tested on Windows 0.21.0 and did not get the same issue. I have a new monitor coming in the mail I'll try this on also.

@jonasschnelli That was 0.20.1

**Comment by jarolrod** [comment]
Do you remember what [Qt](https://www.qt.io) version you used to compile `master` on windows?  
I believe it's possible you may have used an old unsupported version of Qt which led to the GUI looking as it does in your screenshot

**Comment by Bosch-0** [comment]
No I don't, I just built a new system so that information would likely be hard to find

**Comment by jarolrod** [comment]
I can't replicate this on a Windows VM on a MacBook Pro w/ Retina and a native Windows installation on my desktop connected to a 4k monitor. My intuition is that it is related to using an unsupported Qt version as I have seen weird glitches building with an unsupported Qt version on Debian.

Since you cannot replicate the issue yourself either, perhaps this can be closed. If a similar issue is reported again by someone else, then we know we have something to investigate.

**Comment by hebasto** [comment]
Closing for now.

Could be reopened with additional info to reproduce an issue.
