### ISSUE TITLE
macOS 11 (Big Sur) visual bugs

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin-core/gui#136]
Nighy build on Big Sur "dark mode":
![Screenshot 2020-11-24 at 20 13 04](https://user-images.githubusercontent.com/178464/100140847-cda1ca00-2e91-11eb-9cc7-f0afbf542df8.png)

Self compiled on Big Sur "night mode" with depends:
![Screenshot 2020-11-24 at 20 10 38](https://user-images.githubusercontent.com/178464/100141076-1e192780-2e92-11eb-88fc-fb0c8975d2bc.png)

Two major issues:
* [ ] disabling the night mode color palette or adopt it correctly (probably a QT upstream issue)
* [ ] get rid of the white glitch in the debug-window tab-bar-menu 

Qt upstream issue: https://bugreports.qt.io/browse/QTBUG-85546

**Comment by mjdietzx** [comment]
I also noticed what seems to be a bug on Big Sur. When I go to send a transaction from my encrypted wallet, I get a popup that says "Unlock wallet". I enter the correct passphrase, but no matter what the "OK" button stays disabled and can't be clicked. Usually I'd expect once you enter at least 1 char into the passphrase input, that button would become enabled/clickable

**Comment by goums** [comment]
I've tried to update the `QPalette` and the `styleSheet` of the widgets to fix the display glitches, but I didn't manage to fix them as the bugs are directly in the `QMacStyle` widgets implementations.

The QT team is working on it,  but the underlying QT issues will probably take some time to be resolved and is tagged for QT6:
https://bugreports.qt.io/browse/QTBUG-86513

So one solution instead of waiting for QT6 release (and hoping for QMacStyle to be fixed) could be to force `QApplication` to use the default `"Fusion"` style on macos: 
https://doc.qt.io/qt-5/gallery.html

This is a one line change, no added dependencies, and it supports Light /  Dark modes out of the box.

- Some screenshots using Fusion on DarkMode : 
![image](https://user-images.githubusercontent.com/5577626/102623653-22f49280-4143-11eb-81b5-277ee90eb433.png)
![image](https://user-images.githubusercontent.com/5577626/102623667-2ab43700-4143-11eb-86ea-b76f59a3bf10.png)
![image](https://user-images.githubusercontent.com/5577626/102623689-343d9f00-4143-11eb-8622-aceb0da2576f.png)
![image](https://user-images.githubusercontent.com/5577626/102623706-3b64ad00-4143-11eb-829b-11f8961cea63.png)
![image](https://user-images.githubusercontent.com/5577626/102623738-44557e80-4143-11eb-90e9-14da4cbc6fbc.png)

- Some screen shot using Fusion on Light Mode : 
![image](https://user-images.githubusercontent.com/5577626/102624413-4704a380-4144-11eb-9d2c-e87ed204b487.png)
![image](https://user-images.githubusercontent.com/5577626/102624431-4cfa8480-4144-11eb-9e11-0306dd9afccf.png)
![image](https://user-images.githubusercontent.com/5577626/102624472-58e64680-4144-11eb-9e92-2460d9382e4d.png)
![image](https://user-images.githubusercontent.com/5577626/102624524-6b608000-4144-11eb-942f-9c1d67d5c939.png)

**Comment by jonasschnelli** [comment]
@goums: can the fusion style be a runtime option? Or even a startup ENV parameter?

**Comment by goums** [comment]
Yes, according to the doc, it can be either set with a command line argument or an environment variable.
https://doc.qt.io/qt-5/qapplication.html#QApplication

I got an error `Invalid parameter -style` if I try to add it to the command line, but it works nice if I use the environment variable: `QT_STYLE_OVERRIDE =fusion`.

It can be set on the Project > Build & Run > Run > Environment : 
![image](https://user-images.githubusercontent.com/5577626/102658481-ee4efe00-4177-11eb-8285-3d9e7be552e0.png)

NB: you need to fetch #154 to have the icon colorized on macos dark mode

**Comment by hebasto** [comment]
@jonasschnelli 
> @goums: can the fusion style be a runtime option? Or even a startup ENV parameter?

I think the former is disabled since https://github.com/bitcoin/bitcoin/pull/16578.

**Comment by hebasto** [comment]
A workaround is suggested in #177.

**Comment by hebasto** [comment]
@jonasschnelli 

It seems the most of visual bugs are gone after Qt bumping to 5.12.10 (https://github.com/bitcoin/bitcoin/pull/21376).

A few things left like https://bugreports.qt.io/browse/QTBUG-86513.

Efforts to support the dark mode are tracked in #154.

Maybe, there are no reasons to keep this issue opened?

**Comment by hebasto** [comment]
It looks that after https://github.com/bitcoin/bitcoin/pull/22054 is merged this issue could be closed.
