### ISSUE TITLE
Selected peer in the "Peers" tab gets unselected if any previous peer disconnects

### ISSUE THREAD

**Issue by hebasto** [bitcoin-core/gui#160]
On master(209974d379e5c2f32f9f691c992a2fb58be2abf2) the selected peer in the "Peers" tab gets unselected if any previous peer (in the upper rows) disconnects.

**Step 1** -- connected three peers, and "peerC" has been selected:
![Screenshot from 2020-12-22 15-04-19](https://user-images.githubusercontent.com/32963518/102891836-92ca8c00-4467-11eb-957c-bf6f25ed917c.png)

**Step 2** -- new connected peers ("peerD") do not hurt:
![Screenshot from 2020-12-22 15-04-30](https://user-images.githubusercontent.com/32963518/102891955-ca393880-4467-11eb-954a-b5a7d75b5e71.png)

**Step 3** -- but disconnection of any peer from upper rows (e.g., "peerB") causes the loss of peer selection:
![Screenshot from 2020-12-22 15-05-28](https://user-images.githubusercontent.com/32963518/102892156-2439fe00-4468-11eb-913e-100e096cb0d9.png)

**Comment by thantkyaw1** [comment]
Bug

**Comment by jarolrod** [comment]
This bug no longer operates in the way described. I have not investigated fully, but I believe that #18 fixed this bug as it is currently described. There is *still* a bug related to peer selection that exists and it is fixed by #164.

**New Bug:**
on `master`, if you select a peer, and a peer above it disconnects or is disconnected, the selection will **slip** to the next available peer.

| Select Peer  6   | Disconnect Peer 0  |
| --------------- | ------------------- |
| ![Screen Shot 2021-06-06 at 9 17 11 PM](https://user-images.githubusercontent.com/23396902/120947119-be3aed80-c70c-11eb-99e1-ad9a739df5be.png) | ![Screen Shot 2021-06-06 at 9 17 48 PM](https://user-images.githubusercontent.com/23396902/120947129-c430ce80-c70c-11eb-9c5a-8b4f32a07d7f.png) |

As shown in the screenshots above, we start by selecting `Peer 6: 149.248.3.82:38333`. `Peer 0` is then disconnected, our selection then slips to `Peer 7: 88.99.101.67:38333`.

**#164 Fixes New Bug:**
So while the bug has changed, I can confirm that #164 fixes this.


| Select Peer  9   | Disconnect Peer 1  |
| --------------- | ------------------- |
| ![pr-start](https://user-images.githubusercontent.com/23396902/120947607-04448100-c70e-11eb-9794-5db5de86aea8.png) | ![pr-disconnect](https://user-images.githubusercontent.com/23396902/120947622-0d355280-c70e-11eb-8379-1a5e463f0ad7.png) |

The screenshots above were taken on Linux on branch #164. We can see that we start with `Peer 9: 149.248.3.82:38333`, then we disconnect `Peer 1`. Our selection remains with `Peer 9` and does not slip.
