### ISSUE TITLE
The GUI appears non-responsive when the 'still syncing' overlay is visible

### ISSUE THREAD

**Issue by statusquont** [bitcoin-core/gui#22]
After the initial install there is an overlay that provides a description and progress of syncing. If a user clicks on the main UI buttons (Overview, Send, Receive, Transactions) while that overlay is visible, nothing seems to happen. The buttons respond as if clicked (background color changes) but other than that nothing seems to respond. if you look REALLY closely, you can see that actually the UI is responding and changing, but it's masked out behind the overlay screen.

Two suggestion, in my personal order of preference:

1. Clicking anywhere outside of the overlay just closes the overlay.
2. The overlay covers everything and you're essentially forced into clicking the 'Hide' button to reveal the UI behind it.

![image](https://user-images.githubusercontent.com/15948511/86391516-8b1bee80-bc5f-11ea-9301-10478a8a8c18.png)

There's a short video of the behavior posted here:
https://twitter.com/statusquont/status/1278465322278948864

**Comment by hebasto** [comment]
> Two suggestion, in my personal order of preference:
> 
> 1. Clicking anywhere outside of the overlay just closes the overlay.
> 
> 2. The overlay covers everything and you're essentially forced into clicking the 'Hide' button to reveal the UI behind it.

What if Overview / Send / Receive / Transactions would disabled until the "Hide" button is pressed?

**Comment by statusquont** [comment]
That would probably work too, especially if it's combined with this suggestion of making the Primary action item stand out visually: https://github.com/bitcoin-core/gui/issues/24

**Comment by Saibato** [comment]
> That would probably work too, especially if it's combined with this suggestion of making the Primary action item stand out visually: #24

Tyi, the progress bar on the bottom should have already this functionality , and also the sync icon most right on the bottom of the main windows, btw if you hover about icons they hint an info about what they do, but I also would vote for, a button *show detail about sync* in the information window.

In general since the UI is often the first encounter, the first user view is something that tents to fade while dev, since its difficult to forget about what you know about a given software.

**Comment by hebasto** [comment]
@statusquont @Saibato Mind testing #30?
