### ISSUE TITLE
User Display Language broken on 0.21.1

### ISSUE THREAD

**Issue by pcharest** [bitcoin-core/gui#315]
An old node was running with the french interface. When i updated it to 0.21.1 i notice the interface became in english. I checked the setting and 'français' was written. I tried to put it back in english to reput it in french but the interface is always in english. I tried spanish, the language interface change. So french language seem broken in bitcoin core qt with this release. I install the 0.21.0 version and the interface was working in french.

I tried with a new bitcoin core node on 2 others computers and same behavior (Windows 10 and Ubuntu 20.04).

I took the binary from https://bitcoincore.org/bin/bitcoin-core-0.21.1/ and validate the checksum.

**Comment by hebasto** [comment]
@pcharest 

Indeed, as a part of v0.21.1 release process all translations were updated in https://github.com/bitcoin/bitcoin/commit/ab205181912e83166496f0e7a1f5a1879fcd376f from the [Transifex.com](https://www.transifex.com/bitcoin/bitcoin).

At that time the translation for French (fr) was reverted to the original English content. Accordingly to the Transifex history, it was done by Transifex user [liberteefreedom514mtl](https://www.transifex.com/user/profile/liberteefreedom514mtl/) on 2021-04-08. This user is a member Transifex.com since 2021-04-07.

I can see two options:
- contact to French language coordinator on Transifex.com
- fix French translation on Transifex.com by yourself

**Comment by hebasto** [comment]
@laanwj 

It looks like the second case of translation vandalism on Transifex.com recently :disappointed:

**Comment by jarolrod** [comment]
Maybe the translation migration scripts can alert when there's a massive change between the current translation file and the soon-to-be new file?

**Comment by hebasto** [comment]
@pcharest 

Basing on your :+1: under https://github.com/bitcoin-core/gui/issues/315#issuecomment-832015246, and considering that we have nothing to do in this repo to fix the described issue, closing it.
