### ISSUE TITLE
Sign PSBT: Can't verify change output

### ISSUE THREAD

**Issue by kallerosenbaum** [bitcoin-core/gui#732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

When I load a PSBT from file to sign it, the dialog that appears looks like this:

![Screenshot from 2023-05-19 10-02-22](https://github.com/bitcoin-core/gui/assets/1530071/8e466101-4416-4f9a-bf9c-2d1c2bc3d1ee)

There's no way for me to know that the second output belongs to me (it does). Without knowing this I'd feel really uncomfortable signing the PSBT.

### Expected behaviour

The change output should be marked as belonging to me.

### Steps to reproduce

Open a PSBT file that has one output for the payee (not yours) and one output to you (as change)

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

25.0rc2

### Operating system and version

Debian 11

**Comment by furszy** [comment]
Small note about this.
This would work if the change address was previously recorded by the wallet (used in a previous tx). If you just obtained it by a `getrawchangeaddress` RPC call, the wallet will currently not detect it as change. Only will detect it as yours (reasons are explained in #25979).

So, would say to present it as "own address" in the dialog instead of checking whether is change or not (external addresses should be presented as yours too).

**Comment by kallerosenbaum** [comment]
I'll explain better what I do to trigger this, to make sure we're talking about the same issue.

1. Create a new wallet A on regtest, on an offline machine.
2. `listdescriptors` on A and save the result
3. Create a new blank wallet B on another machine
4. `importdescriptors` on B using the result from step 2
5. Get a new address from B and send coins to that address from another wallet
6. In the GUI of B make a transaction to an external address, and make sure to have a change output
7. Save the PSBT to file
8. Open PSBT file it in the GUI of A.

**Comment by kallerosenbaum** [comment]
I don't consider this as a mere inconvenience, but as a security issue. I can't sign this transaction because I don't know which of the outputs, if any, belongs to me. If people do sign these transactions, they're going to be vulnerable to scammers.

If the fix is hard to do, I think the "sign PSBT" feature should be removed from the GUI, as a security measure, until the issue is fixed.

**Comment by furszy** [comment]
My note was for other devs. Based on your comments, you want to get a visual distinction on addresses owned by the signer wallet in the dialog. Which is doable and not hard to do.
My comment was just referring to the `IsMine(addr)` usage instead of the `IsChange(addr)`. Which fulfills the required purposes in the same way (and also accepts external addresses which is more accurate).

**Comment by kallerosenbaum** [comment]
Got it, thanks!

**Comment by Dukdig2325** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### Current behaviour
> 
> When I load a PSBT from file to sign it, the dialog that appears looks like this:
> 
> ![Screenshot from 2023-05-19 10-02-22](https://github.com/bitcoin-core/gui/assets/1530071/8e466101-4416-4f9a-bf9c-2d1c2bc3d1ee)
> 
> There's no way for me to know that the second output belongs to me (it does). Without knowing this I'd feel really uncomfortable signing the PSBT.
> 
> ### Expected behaviour
> 
> The change output should be marked as belonging to me.
> 
> ### Steps to reproduce
> 
> Open a PSBT file that has one output for the payee (not yours) and one output to you (as change)
> 
> 
> ### Relevant log output
> 
> _No response_
> 
> ### How did you obtain Bitcoin Core
> 
> Pre-built binaries
> 
> ### What version of Bitcoin Core are you using?
> 
> 25.0rc2
> 
> ### Operating system and version
> 
> Debian 11
> 
> ### Machine specifications
> 
> _No response_

**Comment by hernanmarino** [comment]
Hey @kallerosenbaum , you are welcome to take a look at this PR I 've just uploaded to address your issue: https://github.com/bitcoin-core/gui/pull/740
