### ISSUE TITLE
gui: node shutting down after incorrect proxy IP address input

### ISSUE THREAD

**Issue by nbit846** [bitcoin-core/gui#809]
### Issues, reports or feature requests related to the GUI should be opened directly on the GUI repo

- [X] I still think this issue should be opened here

### Report

My node was running fine until I decided to change the setting under the nerwork tab, I checked the box for "Use separate SOCKS5 proxy to reach peers via Tor onion services" and on Proxy IP box i put 127.0.0.1:9150, on Port box 9150. When I tried to restart the node it wont start anymore, it gives me "Error 127.0.0.1:9150 incorrect Proxy" and it shuts down immediately. What can I do to get the node to start again?  the GUI is not even starting. I just stared exploring with bitcoin nodes and Im not knowledgable at all, any help will be greatly appreciated. Im running the node on Debian Linux.

**Comment by willcl-ark** [comment]
Hi @nbit846,
 
This issue tracker is supposed to be used to track technical issues related to the Bitcoin Core GUI code base.

General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com/) or the #bitcoin IRC channel on the [Libera Chat](https://libera.chat/) network.

In your case I'd advise checking the bitcoin data directory (`~/.bitcoin`) while the node is not running. You should find a file named `settings.json` which may be persisting the erroneous setting. This can be removed and the node then restarted.

That said, I don't experience the same issue as you when specifying a bad port in that dialogue box, so I'm not totally convinced this is the root cause of your issue (nor that the above step will solve it). Are the any other errors printed in `~/.bitcoin/debug.log`?

**Comment by nbit846** [comment]
I didnt see any other errors printed just this:
2024-03-27T20:18:53Z Loaded 64927 addresses from peers.dat  352ms
2024-03-27T20:18:53Z init message: Loading banlist…
2024-03-27T20:18:53Z SetNetworkActive: true
2024-03-27T20:18:53Z Error: Invalid -onion address or hostname: '127.0.0.1:9050:9050'
2024-03-27T20:19:06Z Shutdown: In progress...
2024-03-27T20:19:06Z scheduler thread exit
2024-03-27T20:19:06Z Flushed fee estimates to fee_estimates.dat.
2024-03-27T20:19:06Z Shutdown: done

**Comment by willcl-ark** [comment]
Yeah. It should not allow port to be duplicated as per this line:

2024-03-27T20:18:53Z Error: Invalid -onion address or hostname: '127.0.0.1:9050:9050'

**Comment by nbit846** [comment]
I was able to start the node by deleting only the hostname on the settings.json. Thank you so much

**Comment by pablomartin4btc** [comment]
Shouldn't the title of the issue be updated? Perhaps adding " _- root cause: incorrect proxy IP address input_" or something? It'll be more useful navigating thru the issues list I think.
